### PR TITLE
Add stake2earn profile description and logo

### PR DESCRIPTION
**Pull request by AlexDCryptoC**

### CODE REVIEW

**Comment by AlexDCryptoC** [comment]
eb0de54c427cc1ee288878cd9ab909afdc8d1ac472c0fda1d4622b36a26340d2

**Comment by svanurin** [comment]
> eb0de54c427cc1ee288878cd9ab909afdc8d1ac472c0fda1d4622b36a26340d2

Thanks for the pull request! It seems that you have deleted info about all other PoSes and their logos. Do you know how to revert your change and make an addition, leaving others info?

**Comment by AlexDCryptoC** [comment]
Sorry for deleting the other stuff. I have updated the PR with new info. Thanks!

**Comment by svanurin** [comment]
It seems like still some deletions. so I'm closing this PR. But no problem, we will take your info and upload it. Your logo and info will be seen in a couple of hours.

**Pull request closed without merging**
